name: flutter_template
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  #State management
  hooks_riverpod: ^2.3.2

  #Icons
  cupertino_icons: ^1.0.5
  ionicons: ^0.2.2

  #Networking
  retrofit: ^4.0.1
  supabase_flutter: ^1.5.0
  
  #Others
  i18n: ^4.0.2
  get_it: ^7.2.0
  floor: ^1.4.1
  auto_route: ^6.0.0+1
  auto_route_generator: ^6.0.0
  flutter_dotenv: ^5.0.2
  equatable: ^2.0.5
  envify: ^2.0.3

dev_dependencies:
  
  build_runner: ^2.3.3
  envify_generator: ^2.0.3
  flutter_lints: ^2.0.0
  lint: ^2.0.1
flutter:
  uses-material-design: true

assets:
  - .env.development
  - .env.production
  - .env
